name: Publish

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'
      
      - name: Restore
        run: dotnet restore ./StajApp.sln

      - name: Build
        run: dotnet build ./StajApp.sln --configuration Release

      - name: Publish
        run: dotnet publish ./StajApp.sln --configuration Release --no-build
